GET http://sibchudo.local/api/cat?criteria={"gender":"female"}
Accept: application/json

###
POST http://sibchudo.local/api/cat?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTk0MDIyNzAsImV4cCI6MTU5OTQ3NDI3MCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibmlrX21ha0Biay5ydSJ9.ZMQf_CEuiEgcfBSTaXn09xh44evVySyByPJHCiUhm_7XivNLUjapzpQZO-7y7sDP0TiHKOI5_qusl3ayhLstsKZWfBKPpRCVI2tE6ysEYhqZvGeblu2RHZX2xL9MtwS7R1QrUCdIE4Wfsw3PYwJYF_xHpKHcw-qZZ_0Ws9noX_DmVlqvD92JXDqPK4OTitMZsVII1UV472ckkrks53ThsqdxZ4u-qIhFt819pwCCtDbysge14KjA8uQ9WZTlyH7vCXDgGknLs6o6fi-rA44sYVmNZW4hQinSa05exvWJtgiiVp5GD3AIN0qGG1dy35ltXQDgzTrImLTtKKqRbYwpMgruVehnB9dz06zMTlHvK8-9ljkfIIS6_bG_iI2Ndto_PdvumrUITBvXJjsqZN9BLzQpDlihYlwCy7e01Mdq9omuP4u-Frf3oeDukHCaXm103ZBOp6OHtCIubbGG4o8RKOv3zJciA16Enylji4YFksMxNcY3ehhhRVJfTlqWMxuThsYXpU4GE9a02EUySoV6rI1UrJECgwiiAYqqakHREQqL_hq2Leg9jUnKDMERl4uUAZztjc0ZUSf6Adlud2TWqCGBeG-rfv71r6cbZUoo-f9IhgG-Dt1AemLVCKB_gpY4ZZor-vF88jz1HQCabekG3PHXgmGnWh-C7F-ABz2gAmU
Content-Type: application/json

{
  "name": "Котик",
  "gender": "female",
  "color": {
    "breed": 1,
    "baseColor": 1,
    "baseColorAdditional": 1,
    "code0": 1,
    "code1": 1,
    "code2": 1,
    "code3": 1,
    "tail": 1,
    "eyes": 1,
    "ears": 1
  },
  "catClass": 1,
  "title": 1,
  "litter": 1,
  "community": 1,
  "owner": 1,
  "status": 1
}

###

PUT http://sibchudo.local/api/cat/1
Content-Type: application/json

{
  "name": "КотикEdit",
  "gender": "male",
  "color": {
    "breed": 1,
    "baseColor": 1,
    "baseColorAdditional": 1,
    "code0": 1,
    "code1": 1,
    "code2": 1,
    "code3": 1,
    "tail": 1,
    "eyes": 1,
    "ears": null
  },
  "catClass": 1,
  "title": 1,
  "litter": 1,
  "community": 1,
  "owner": 1,
  "status": 1
}