
POST http://sibchudo.local/api/session
Content-Type: application/json

{
  "username": "nik_mak@bk.ru",
  "password": "123"
}

###

GET http://sibchudo.local/api/session?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE1OTk0MDI2MTIsImV4cCI6MTU5OTQwMjYxMywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibmlrX21ha0Biay5ydSJ9.TEdoWTaSWOsfg-1Mvd5Ka6UxEE4m6OEhQRHoOpEne7PhFlzn-0klguEMupsIMEK0VmY_s7cg7HyVpStr0Qt8ZroQub3M-QcY8B4-lQCT1nV8gQd-bNJEkfivUWSlWjZZp8fzMf05eLruid_rVgndlm8Hn_8lmWo03K04qm7fCL63LQ3aslSRIejNk1GtYh0N_umdg7CQUuCBeI9O6-mhkVM564SHj4uUXaFWrEr0BoJ__fbKcvn0KMXI1peRQgCwKfS6F1L_7pqMGxqhWNJ1lQeqo3eLcUY49i0GB3gYqKw0oOYkay8_TOtN7BNaIsT3EMzCixEYi3RW3INkCRQVKobXeHMt7PP2YR_epSyQCvexhq4vp0X-C-CZj6Xk36ErEilF2_SZLBoiacMn-O-2GnGbpkASGLZsRwrrVsJPEIU7g7H_dOc2VCQjUvmVZw-mv_38Eq1x0ojdD-yY26TvdYoMsh5FEveICyviNGPxP_F2PJIK0_3Ediew7E_FI4sJkWKH-B0hxvIfSW6orqPSCUkzVmHVCFsLGiP0KOQE7nJUmesqOz5a8q42oB_8gSHmTuStTi6gg2i07nhqko3Twv90rLKMygp7k--9rBqyuy8h9iHUpIvWJ04eFbW3yTIRw25P5NSNzbMiudv97b4MAt9TW_q8nh89BHdVKF_KLTg