INSERT INTO breed(code, name, name_ru)
VALUES ('PER', ' Persian', ' Персидские'),
       ('ACL', ' American Curl longhair', ' Американский кёрл ДШ'),
       ('ABT', ' American bobtail', ' Американский бобтейл'),
       ('BAL', ' Balinese (Balinesian)', ' Балинезийская (Балинез)'),
       ('BLH', ' British longhair', ' Британская длинношерстная'),
       ('CYM', ' Cymric', ' Кимрик'),
       ('JBL', ' Japanese Bobtail longhair', ' Японский бобтейл длинношерстный,'),
       ('KAB', ' Karelian bobtail longhair', ' Карельский бобтейл'),
       ('KBL', ' Kurilian bobtail longhair', ' Курильский бобтейл'),
       ('LPL', ' La Perm longhair', ' Ла Перм длинношерстная'),
       ('MCO', ' Maine coon', ' Мейн-кун'),
       ('MNL', ' Munchkin longhair', ' Манчкин длинношерстный'),
       ('NEB', ' Nebelung', ' Нибелунг'),
       ('NEV', ' Neva maskarade', ' Невская маскарадная'),
       ('NFO', ' Norwegian Forest Cat', ' Норвежская лесная'),
       ('OSL', ' Oriental Semilonghair', ' Ориентальная полудлинношерстная (Мандарин)'),
       ('RAG', ' Ragdoll', ' Рэгдолл'),
       ('RGM', ' Ragamuffin', ' Рагамаффин'),
       ('SBI', ' Sacred birman', ' Бирманская (Священная бирма)'),
       ('SFL', ' Highland Fold', ' Скоттиш-фолд ДШ (Хайленд фолд)'),
       ('SIB', ' Siberian', ' Сибирская'),
       ('SOM', ' Somali', ' Сомалийская (Сомали)'),
       ('SRX', ' Selkirk Rex longhair', ' Селкирк-рекс ДШ'),
       ('SYL', ' Seychellois longhair', ' Сейшельская ДШ'),
       ('TIF', ' Tiffani (Tiffanie)', ' Тиффани (Азиатская ДШ, Махагон, Шантилли)'),
       ('TUA', ' Turkish angora', ' Турецкая ангора'),
       ('TUV', ' Turkish van', ' Турецкая ван'),
       ('URL', ' Ural Rex longhair', ' Уральский рекс длинношерстный'),
       ('URX', ' Ural rex longhair', ' Уральский рекс ДШ'),
       ('YOR', ' York Chocolate', ' Йоркская (Йорк) '),
       ('ABY', ' Abyssinian', ' Абиссинская'),
       ('ACS', ' American Curl shorthair', ' Американский кёрл, Ameerika Curl luhikavaline,'),
       ('ANA', ' Anatolian', ' Анатолийская (Турецкая КШ)'),
       ('ARM', ' Arabia Mau', ' Аравийская Мау'),
       ('ASH', ' American shorthair', ' Американская короткошерстная'),
       ('ASI', ' Asian (tabby, smoke)', ' Азиатская (тэбби, дымчатая)'),
       ('AUM', ' Australian Mist', ' Австралийская дымчатая (Мист)'),
       ('AWH', ' American wirehair', ' Американская жесткошерстная'),
       ('BEN', ' Bengalian (Bengal)', ' Бенгальская'),
       ('BOM', ' Bombay', ' Бомбейская'),
       ('BRA', ' Brasilian Shorthair', ' Бразильская короткошерстная'),
       ('BRI', ' British shorthair', ' Британская короткошерстная'),
       ('BMI', ' Burmilla', ' Бурмилла'),
       ('BUR', ' Burmese (Burma)', ' Бурмезская (Бурманская)'),
       ('CEY', ' Ceylon', ' Цейлонская СНА Chartreux Шартрез (Картезианская)'),
       ('CRX', ' Cornish-rex', ' Корниш-рекс'),
       ('CSP', ' Califomian splendid', ' Калифорнийская сияющая'),
       ('DRX', ' Devon Rex', ' Девон рекс'),
       ('DSX', ' Don Sphinx', ' Донской сфинкс'),
       ('EUR', ' European shorthair (Celtic)', ' Европейская КШ (Кельтская)'),
       ('EXO', ' Exotic shorthair', ' Экзотическая короткошерстная'),
       ('GRX', ' German rex', ' Герман рекс (Немецкий рекс)'),
       ('HHP', ' Household Pet', ' Домашняя кошка'),
       ('HVB', ' Havana brown', ' Гавана браун'),
       ('JAV', ' Javanese', ' Яванезийская'),
       ('JBT', ' Japanese bobtail', ' Японский бобтейл'),
       ('KAN', ' Kanaania', ' Канаани (Канаанская)'),
       ('KAS', ' Karelian Bobtail shorthair', ' Карельский бобтейл КШ'),
       ('KBS', ' Kurilian Bobtail shorthair', ' Курильский бобтейл КШ'),
       ('KOR', ' Korat', ' Корат'),
       ('MAN', ' Manx', ' Мэнкс (Манкс, Мэнская)'),
       ('MAU', ' Egyptian mau', ' Египетская мау'),
       ('MNS', ' Munchkin shorthair', ' Манчкин КШ'),
       ('OCI', ' Ocicat', ' Оцикэт'),
       ('RUS', ' Russian blue', ' Русская голубая'),
       ('SFS', ' Scottish-fold (KH)', ' Скоттиш-фолд (Шотландская вислоухая)'),
       ('SIN', ' Singapura', ' Сингапурская (Сингапура)'),
       ('SNO', ' Snow-shoe', ' Сноу-шу'),
       ('SOK', ' Sokoke', ' Сококе'),
       ('SPH', ' Sphinx (Canadian sphinx)', ' Канадский сфинкс'),
       ('SRS', ' Selkirk Rex shorthair', ' Селкирк рекс короткошерстный'),
       ('MBT', ' Mekong Bobtail', ' Меконгский бобтейл'),
       ('PBD', ' Peterbald', ' Петерболд (Петербургский сфинкс)'),
       ('OKH', ' Oriental shorthair', ' Ориентальная короткошерстная'),
       ('SYS', ' Seychellois shorthair (Siamese bicolour)', ' Сейшельская КШ'),
       ('SIA', ' Siamese', ' Сиамская'),
       ('TBT', ' Thai bobtail', ' Тайский бобтейл'),
       ('THA', ' Thai', ' Тайская'),
       ('TON', ' Tonkinese', ' Тонкинская');
