insert into base_color(code, name, name_ru)
values ('a', 'blue', 'голубой'),
       ('b', 'chocolate (brown, chestnut)', 'шоколадный (коричневый, каштановый, гавана, шампанский)'),
       ('c', 'lilac (lavender)', 'лиловый (лавандовый, платиновый)'),
       ('d', 'red, flame', 'красный'),
       ('e', 'cream', 'кремовый'),
       ('f', 'tortoiseshell', 'черепаховый'),
       ('g', 'blue-cream, blue-tortie', 'голубокремовый, голубочерепаховый'),
       ('h', 'chocolate-tortie', 'шоколадный черепаховый'),
       ('j', 'lilac-tortie', 'лиловый черепаховый'),
       ('n', 'black, ebony, seal, sable, ruddy', 'черный, сил, соболиный, дикий'),
       ('o', 'sorrel, cinnamon, honey соррель,', 'красно-коричневый, коричневый, медовый'),
       ('p', 'beige fawn', 'желто-коричневый,бежевый олененок'),
       ('q', 'sorrel tortie', 'красно-коричневый черепаховый'),
       ('r', 'beige fawn tortie', 'желто-коричневый черепаховый'),
       ('s', 'silver, smoke', 'серебристый, дымчатый'),
       ('w', 'white', 'белый'),
       ('y', 'golden', 'золотистый '),
       ('x', 'unregistered', 'не зарегистрированный, непризнанный окрас');